spring:
  application:
    name: ToDoApi
  profiles:
    active: dev

server:
  port: 8080

management:
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    version: "@project.version@"
    description: "@project.description@"
