spring:
  datasource:
    url: jdbc:h2:file:./data/todoapidb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    defer-datasource-initialization: false
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: never

logging:
  level:
    com.fnavas.todoapi: INFO
    org.springframework: WARN
