INSERT INTO task (title, description, completed, priority, created) VALUES ('Buy groceries', 'Pick up milk, eggs, bread, and vegetables from the supermarket', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Read a book', 'Finish reading the current chapter of the novel', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Go for a run', 'Run 5 kilometers in the park before breakfast', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Write a report', 'Complete the quarterly report for the management team', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Call the dentist', 'Schedule a routine check-up appointment', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Fix the leaking faucet', 'Repair the kitchen faucet that has been dripping for a week', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Prepare presentation', 'Create slides for the Monday morning team meeting', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Clean the garage', 'Sort and discard old items cluttering the garage', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Pay electricity bill', 'Submit the monthly electricity payment before the due date', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Study for exam', 'Review chapters 4 through 7 for the upcoming test', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Update resume', 'Add recent work experience and new skills to the CV', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Water the plants', 'Water all indoor plants and check the soil moisture', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Organize desk', 'Clear clutter and arrange desk supplies neatly', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Send birthday card', 'Mail the birthday card to grandma before Friday', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Back up computer', 'Run a full backup of important files to external drive', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Cook dinner', 'Prepare pasta carbonara for the family tonight', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Schedule meeting', 'Arrange a weekly sync with the development team', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Renew library card', 'Visit the local library to renew the membership card', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Do laundry', 'Wash, dry, and fold all clothes from the laundry basket', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Review pull request', 'Check and comment on the open pull request from the team', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Plan vacation', 'Research destinations and book flights for summer holiday', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Cancel subscription', 'Unsubscribe from the unused streaming service', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Take dog to vet', 'Annual check-up and vaccination for the dog', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Fix website bug', 'Investigate and resolve the login page error reported by users', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Meditate', 'Practice 15 minutes of mindfulness meditation in the morning', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Grocery list', 'Prepare a detailed list before going to the store on Saturday', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Learn Spanish', 'Complete lesson 10 of the Spanish learning app', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Change car oil', 'Take the car to the mechanic for an oil change', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Write blog post', 'Draft an article about the latest technology trends', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Set up CI pipeline', 'Configure GitHub Actions for automated testing', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Sort recycling', 'Separate glass, plastic, and paper for recycling collection', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Call parents', 'Check in with parents and catch up over the phone', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Refactor authentication', 'Clean up the auth module and remove deprecated methods', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Buy birthday gift', 'Find a suitable gift for the friend''s upcoming birthday', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Clean bathroom', 'Scrub tiles, clean toilet, and mop the floor', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Submit tax return', 'Gather documents and file the annual tax return online', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Read documentation', 'Go through the Spring Boot migration guide for version 4', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Attend webinar', 'Join the online seminar about cloud architecture best practices', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Update dependencies', 'Bump all outdated Maven dependencies in the project', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Stretch exercises', 'Follow the 20-minute morning stretching routine', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Write unit tests', 'Increase code coverage for the service layer to 80%', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Paint living room', 'Apply second coat of paint to the living room walls', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Defrost freezer', 'Unplug and defrost the kitchen freezer', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Respond to emails', 'Reply to all pending emails in the inbox', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Configure database', 'Set up connection pooling and tune database parameters', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Watch tutorial', 'Follow the Docker containerization tutorial on YouTube', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Mow the lawn', 'Cut the grass in the front and back yards', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Review budget', 'Analyse monthly expenses and adjust the budget spreadsheet', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Deploy to staging', 'Push the latest release to the staging environment', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Drink more water', 'Aim for at least 8 glasses of water throughout the day', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Organise photos', 'Sort and label photos from the last holiday trip', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Learn Git rebase', 'Study interactive rebase and squash commits workflow', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Replace light bulb', 'Change the broken light bulb in the hallway', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Write meeting notes', 'Summarise the key decisions from today''s meeting', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Implement logging', 'Add structured logging to all API endpoints', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Donate old clothes', 'Pack up unused clothing and drop it at the charity shop', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Vacuum the house', 'Vacuum all rooms and under the furniture', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Setup monitoring', 'Configure Prometheus and Grafana dashboards for the app', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Book flight tickets', 'Purchase round-trip tickets for the conference trip', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Feed the cat', 'Give the cat its morning and evening meals', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Review architecture', 'Evaluate the current microservices architecture for improvements', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Practice guitar', 'Rehearse the new song for 30 minutes after work', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Fix broken link', 'Update the broken hyperlink on the company website footer', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Prepare interview', 'Research the company and practice common interview questions', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Clean kitchen', 'Wipe surfaces, clean the oven, and mop the floor', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Order office supplies', 'Request pens, notebooks, and printer paper from the supplier', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Set fitness goals', 'Define monthly fitness targets and track progress', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Migrate database', 'Run Flyway migration scripts on the production database', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Check smoke alarms', 'Test all smoke detectors and replace batteries if needed', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Design new feature', 'Sketch wireframes for the new user dashboard feature', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Update API docs', 'Refresh the Swagger documentation with new endpoint details', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Go to the gym', 'Complete upper body workout session at the gym', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Write changelog', 'Document all changes for the upcoming software release', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Trim the hedge', 'Cut back the overgrown hedge along the garden fence', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Improve error handling', 'Add meaningful error messages to all exception handlers', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Attend standup', 'Join the daily standup meeting and share progress updates', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Print documents', 'Print boarding passes and hotel confirmation for the trip', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Add input validation', 'Validate all user inputs in the registration form', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Cook meal prep', 'Prepare lunches for the whole week on Sunday afternoon', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Renew passport', 'Apply for passport renewal before the expiry date', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Test REST endpoints', 'Run manual tests on all API endpoints using Postman', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Tidy garden', 'Remove weeds and rake the leaves from the garden path', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Review code style', 'Enforce consistent code style using Checkstyle rules', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Buy new shoes', 'Purchase a pair of running shoes for the upcoming race', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Archive old files', 'Move unused project files to the long-term storage folder', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Implement caching', 'Add Redis caching layer to the most frequent API calls', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Visit the library', 'Return overdue books and borrow two new ones', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Install security updates', 'Apply the latest security patches to the server', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Write cover letter', 'Draft a tailored cover letter for the job application', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Tidy wardrobe', 'Reorganise clothes by season and donate unused items', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Perform code review', 'Review three open pull requests from junior developers', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Check tire pressure', 'Inspect and inflate car tires to the recommended PSI', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Set up local environment', 'Install and configure the development environment from scratch', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Make dentist appointment', 'Book a check-up for next month at the dental clinic', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Write SQL queries', 'Optimise slow-running queries identified in the performance report', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Hang picture frames', 'Mount the new photo frames on the living room wall', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Catch up on news', 'Read the top headlines and industry news for the week', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Document API changes', 'Update the developer wiki with the latest breaking changes', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Refactor tests', 'Eliminate duplicated test setup using shared fixtures', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Plan sprint', 'Organise backlog and assign tasks for the next sprint', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Fix CSS layout', 'Resolve the responsive layout issue on mobile screens', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Take out the trash', 'Empty all bins and place bags outside for collection', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Investigate slow query', 'Profile and fix the database query causing high latency', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Buy new headphones', 'Research and purchase noise-cancelling headphones for work', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Sanitize user input', 'Add input sanitization to prevent XSS vulnerabilities', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Make bed', 'Straighten sheets and arrange pillows every morning', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Update social profile', 'Refresh LinkedIn profile with current role and achievements', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Load test the API', 'Run k6 load tests and analyse response time under stress', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Plant flowers', 'Plant the seasonal flowers in the front garden beds', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Prepare onboarding docs', 'Write a guide for new team members joining the project', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Fix memory leak', 'Identify and resolve the memory leak in the background worker', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Attend conference', 'Participate in the two-day software engineering conference', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Write thank-you note', 'Send a thank-you email after the job interview', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Create Docker image', 'Build and push the production Docker image to the registry', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Setup HTTPS', 'Install SSL certificate and configure HTTPS on the server', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Update test data', 'Refresh the seed data in the test database environment', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Learn Kubernetes', 'Complete the introductory Kubernetes course on the platform', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Clean shower', 'Descale the shower head and clean the tiles thoroughly', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Track expenses', 'Log all purchases from the week into the expense tracker', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Write integration test', 'Add end-to-end test for the task creation workflow', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Charge laptop', 'Plug in the laptop and ensure it reaches full charge overnight', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Update firewall rules', 'Review and tighten firewall rules on the production server', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Research competitors', 'Analyse competitor products and summarise key findings', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Add pagination to UI', 'Implement next/prev controls in the frontend task list view', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Check analytics', 'Review last week''s website traffic in the analytics dashboard', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Remove dead code', 'Delete unused classes and commented-out code blocks', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Prepare demo', 'Set up the demo environment for the client presentation', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Tighten screws', 'Check and tighten all loose screws on furniture', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Fix date format', 'Standardise date format to ISO 8601 across the application', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Grocery shopping', 'Stock up on weekly essentials at the local supermarket', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Review security report', 'Go through the latest vulnerability scan report', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Practice typing', 'Complete a 10-minute touch-typing practice session', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Resize images', 'Compress and resize product images for the website', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Write README', 'Add setup instructions and usage examples to the README file', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Stretch before bed', 'Do a 10-minute stretching routine to relax before sleeping', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Implement rate limiting', 'Add rate limiting to the public API endpoints', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Review sprint goals', 'Check progress against sprint targets and adjust if needed', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Clean coffee machine', 'Descale and clean the office coffee machine', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Update README badges', 'Add build status and coverage badges to the project README', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Buy printer ink', 'Order replacement ink cartridges for the home printer', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Test mobile view', 'Check application layout on different mobile screen sizes', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Plan weekly meals', 'Decide on recipes and write the shopping list for the week', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Submit bug report', 'File a detailed bug report for the issue found in production', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Improve search', 'Enhance task search to support partial and fuzzy matching', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Check email filters', 'Review and update inbox filters to reduce spam', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Renew insurance', 'Compare quotes and renew the home insurance policy', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Add sorting to UI', 'Allow users to sort the task list by different columns', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Record screencast', 'Create a short demo video for the new feature release', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Visit dentist', 'Attend the scheduled dental cleaning appointment', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Merge feature branch', 'Merge the completed feature branch into the main branch', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Plan team outing', 'Organise a team lunch or activity for next Friday', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Wash the car', 'Give the car a thorough wash and wax in the driveway', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Review OKRs', 'Assess quarterly objectives and key results with the manager', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Fix broken test', 'Investigate and repair the failing test in the CI pipeline', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Enable dark mode', 'Add a dark mode toggle to the application settings', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Fill water bottles', 'Refill all reusable water bottles for the week', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Analyze logs', 'Review server logs for errors and unusual activity', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Design logo', 'Create a new logo concept for the product rebrand', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Lock the bike', 'Always lock the bike securely when leaving it outside', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Add soft delete', 'Implement soft delete with deletedAt timestamp on Task entity', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Test edge cases', 'Write tests for null inputs and boundary conditions', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Charge phone', 'Keep phone charged above 20% throughout the day', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Setup VPN', 'Configure company VPN on the new laptop', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Interview candidate', 'Conduct technical interview for the backend engineer role', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Tidy kitchen drawers', 'Sort and organise utensils in the kitchen drawers', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Upgrade Java version', 'Migrate the project from Java 17 to Java 21', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Check backup status', 'Verify that automatic backups are running successfully', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Prepare flashcards', 'Create study flashcards for the certification exam', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Send invoice', 'Email the monthly invoice to the client by end of day', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Test pagination', 'Verify that all pagination parameters work correctly in the API', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Restart the server', 'Schedule a maintenance restart of the production server', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Read research paper', 'Go through the distributed systems research paper', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Clean windows', 'Wipe down all windows inside and outside the house', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Tag the release', 'Create a git tag for the new production release version', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Prepare Q&A session', 'Compile a list of expected questions for the demo Q&A', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Buy vitamins', 'Purchase daily vitamins and supplements at the pharmacy', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Optimize build time', 'Reduce the Maven build time by enabling parallel compilation', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Restock first aid kit', 'Check and replenish supplies in the home first aid kit', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Write data migration', 'Script to backfill missing created dates in existing records', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Eat breakfast', 'Have a healthy breakfast before starting work each morning', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Update Postman collection', 'Add new endpoints and examples to the Postman collection', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Setup branch protection', 'Require PR reviews before merging to the main branch', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Go to bed early', 'Aim to be in bed by 10:30pm for a full 8 hours of sleep', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Profile application', 'Use JVM profiler to identify CPU and memory hotspots', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Take meeting notes', 'Document action items during the all-hands meeting', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Turn off unused lights', 'Switch off lights in empty rooms to save energy', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Refactor repository', 'Move custom query methods to a proper repository interface', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Plan content calendar', 'Schedule blog posts and social media content for the month', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Fix spelling errors', 'Proofread all user-facing text and correct typos', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Attend yoga class', 'Participate in the weekly yoga session at the community centre', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Configure alerts', 'Set up email and Slack alerts for critical application errors', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Research new library', 'Evaluate Testcontainers for integration testing improvements', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Write ADR', 'Document the architecture decision record for pagination design', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Remove unused imports', 'Clean up unnecessary imports across all Java source files', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Iron clothes', 'Iron the shirts and trousers for the working week', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Update project board', 'Move completed tasks to done column on the project board', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Buy coffee beans', 'Order a fresh bag of specialty coffee beans online', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Add API versioning', 'Introduce versioning strategy for future API changes', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Practice presentation', 'Rehearse the product demo at least twice before the meeting', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Clean mouse and keyboard', 'Wipe down peripherals with a disinfectant cloth', TRUE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Implement health check', 'Add Spring Actuator health endpoint to the application', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Create runbook', 'Write operational runbook for the deployment process', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Plan birthday party', 'Organise catering, venue, and invitations for the party', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Enable gzip compression', 'Configure HTTP response compression for the REST API', FALSE, 'MEDIUM', CURRENT_DATE);
INSERT INTO task (title, description, completed, priority, created) VALUES ('Sleep 8 hours', 'Maintain a consistent sleep schedule for better productivity', TRUE, 'MEDIUM', CURRENT_DATE);
